# Generated by Django 6.0 on 2026-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='colour',
            field=models.CharField(max_length=100),
        ),
    ]
