# Generated by Django 6.0 on 2026-03-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='colour',
        ),
    ]
