# Generated by Django 6.0 on 2026-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_productvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='added_date',
            field=models.DateField(auto_now_add=True, default='2026-03-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
