# Generated by Django 6.0 on 2026-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_productvariant_added_date_productvariant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
