# Generated by Django 6.0 on 2026-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logo/'),
        ),
    ]
