# Generated by Django 6.0 on 2026-06-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='variant',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='area',
            field=models.CharField(default=None, max_length=250, verbose_name='Area, Street, Sector, Village'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(default=None, max_length=250, verbose_name='Town/City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='flat',
            field=models.CharField(default=None, max_length=250, verbose_name='Flat, House no., Building, Company, Apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='full_name',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='mobile_number',
            field=models.CharField(default=None, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
